# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-techspike-customer-registry-alert:
    build:
      target: development
    image: ffc-techspike-customer-registry-alert-development
    container_name: ffc-techspike-customer-registry-alert-development
    ports:
      - "4004:3000"
      - "9244:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
