services:
  ffc-techspike-customer-registry-alert:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry-alert
    container_name: ffc-techspike-customer-registry-alert
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-alert-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      CUSTOMERREGISTRYALERTREQUEST_QUEUE_ADDRESS: ${CUSTOMERREGISTRYALERTREQUEST_QUEUE_ADDRESS:-ffc-techspike-customer-registry-alert}${MESSAGE_QUEUE_SUFFIX}
      NOTIFY_TEMPLATE_ID_CUSTOMER_REGISTRY_ALERT: ${NOTIFY_TEMPLATE_ID_CUSTOMER_REGISTRY_ALERT}
      NOTIFY_CUSTOMER_REGISTRY_API_KEY: ${NOTIFY_CUSTOMER_REGISTRY_API_KEY}