services:
  ffc-techspike-customer-registry-alert:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry-alert
    container_name: ffc-techspike-customer-registry-alert
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-alert-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
